export const ADD_FAVORITE = 'ADD_FAVORITE'

export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

export const ADD_CITY_WEATHER = 'ADD_CITY_WEATHER'

export const UPDATE_SELECTED_CITY = 'UPDATE_SELECTED_CITY'

export const SET_IS_HOME_VIEW_SHOWN = 'SET_IS_HOME_VIEW_SHOWN'

export const SET_IS_FERENHEIT = 'SET_IS_FERENHEIT'
